name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' , '3.1']
        minimal: [ false, true ]
    name: Ruby ${{ matrix.ruby }} tests, minimal=${{ matrix.minimal }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        env:
          MINIMAL: ${{ matrix.minimal }}
        run: bundle exec rake
